version: "3.8"

services:
  cats-db:
    image: postgres
    container_name: cats-db
    restart: always
    tty: true
    networks:
      - cats-network
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=leo123
      - POSTGRES_DB=cats

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cats-backend
    restart: always
    tty: true
    networks:
      - cats-network
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cats-db:5432/cats
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=leo123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update  
      - SPRING_JPA_SHOW_SQL=true               
    depends_on:
      - cats-db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cats-frontend
    restart: always
    tty: true
    networks:
      - cats-network
    ports:
      - "3000:3000"
    depends_on:
      - backend

  zabbix-db:
    image: mysql:5.7
    container_name: zabbix-db
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pwd
      MYSQL_ROOT_PASSWORD: root_pwd
    volumes:
      - zabbix-db-data:/var/lib/mysql
    networks:
      - cats-network

  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: zabbix-db
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pwd
      MYSQL_ROOT_PASSWORD: root_pwd
    depends_on:
      - zabbix-db
    ports:
      - "10051:10051"
    networks:
      - cats-network
  
  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: zabbix-db
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pwd
      MYSQL_ROOT_PASSWORD: root_pwd
    depends_on:
      - zabbix-server
    ports:
      - "8081:8080"
    networks:
      - cats-network
  
  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    environment:
      ZBX_SERVER_HOST: zabbix-server
    depends_on:
      - zabbix-server
    ports:
      - "10050:10050"
    networks:
      - cats-network


networks:
  cats-network:
    driver: bridge

volumes:
  db:
    driver: local
  zabbix-db-data:
    driver: local
