version: "3.8"

services:
  cats-db:
    image: postgres
    container_name: cats-db
    restart: always
    tty: true
    networks:
      - cats-network
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cats

networks:
  cats-network:
    driver: bridge


volumes:
  db:
    driver: local