spring:
  application:
    name: Cats Service
  datasource:
    url: jdbc:postgresql://3.144.71.109:5432/cats
    username: postgres
    password: leo123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
