name: Deploy Catservice

on:
    push:
        branches: [main, staging]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                distribution: 'corretto'
                java-version: '21'
            
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: '14'
            
            - name: Build project
              run: |
                cd backend
                mvn clean install -DskipTests
            
            - name: Dockerhub Login
              run: docker login -u leonadolnym -p 'leo10203045@n'

            - name: Build docker image front
              run: |
                cd frontend
                docker build -t leonadolnym/cat-service-frontend .

            - name: Build docker image back
              run: |
                cd backend
                docker build -t leonadolnym/cat-service-backend .

            - name: Push image front
              run: |
                cd frontend
                docker push leonadolnym/cat-service-frontend
            
            - name: Push image back
              run: |
                cd backend
                docker push leonadolnym/cat-service-backend
            
            - name: Pull Zabbix images
              run: |
                 docker pull zabbix/zabbix-server-mysql:latest
                 docker pull zabbix/zabbix-web-nginx-mysql:latest
                 docker pull zabbix/zabbix-agent:latest
                 docker pull mysql:5.7
    
    deploy:
      needs: build
      runs-on: self-hosted
      steps:
        - name: Dockerhub Login
          run: docker login -u leonadolnym -p 'leo10203045@n'

        - name: Pull backend image
          run: docker pull leonadolnym/cat-service-backend:latest  
        
        - name: Pull frontend image
          run: docker pull leonadolnym/cat-service-frontend:latest

        - name: Stop and remove existing containers
          run: |
               docker stop cats-db cat-service-backend cat-service-frontend zabbix-db zabbix-server zabbix-web zabbix-agent || true
               docker rm cats-db cat-service-backend cat-service-frontend zabbix-db zabbix-server zabbix-web zabbix-agent || true
          
        - name: Create Docker network
          run: |
               docker network create cats-network || true

        - name: Start PostgreSQL container
          run: |
              docker run -d --name cats-db -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=leo123 -e POSTGRES_DB=cats -p 5432:5432 postgres:alpine

        - name: Start backend container
          run: |
               docker run -d -p 8080:8080 --name cat-service-backend leonadolnym/cat-service-backend:latest

        - name: Start frontend container
          run: |
            docker run -d -p 3000:3000 --name cat-service-frontend leonadolnym/cat-service-frontend:latest

        - name: Start Zabbix database
          run: |
              docker run -d --name zabbix-db \
                  -e MYSQL_DATABASE=zabbix \
                  -e MYSQL_USER=zabbix \
                  -e MYSQL_PASSWORD=zabbix_pwd \
                  -e MYSQL_ROOT_PASSWORD=root_pwd \
                  -v zabbix-db-data:/var/lib/mysql \
                  --network cats-network \
                  mysql:5.7

        - name: Initialize Zabbix database
          run: |
               if ! docker exec -it zabbix-db mysql -u root -proot_pwd -e "USE zabbix; SHOW TABLES;" | grep -q "users"; then
               docker exec -it zabbix-db mysql -u root -proot_pwd zabbix < /usr/share/zabbix-sql-scripts/mysql/server.sql
               fi


        - name: Start Zabbix server
          run: |
                docker run -d --name zabbix-server \
                  -e DB_SERVER_HOST=zabbix-db \
                  -e MYSQL_DATABASE=zabbix \
                  -e MYSQL_USER=zabbix \
                  -e MYSQL_PASSWORD=zabbix_pwd \
                  -e MYSQL_ROOT_PASSWORD=root_pwd \
                  --network cats-network \
                  -p 10051:10051 \
                  zabbix/zabbix-server-mysql:latest

        - name: Start Zabbix web interface
          run: |
                docker run -d --name zabbix-web \
                    -e ZBX_SERVER_HOST=zabbix-server \
                    -e DB_SERVER_HOST=zabbix-db \
                    -e MYSQL_DATABASE=zabbix \
                    -e MYSQL_USER=zabbix \
                    -e MYSQL_PASSWORD=zabbix_pwd \
                    -e MYSQL_ROOT_PASSWORD=root_pwd \
                    --network cats-network \
                    -p 8081:8080 \
                    zabbix/zabbix-web-nginx-mysql:latest 

        - name: Start Zabbix agent
          run: |
               docker run -d --name zabbix-agent \
                -e ZBX_SERVER_HOST=zabbix-server \
                --network cats-network \
                -p 10050:10050 \
                zabbix/zabbix-agent:latest